# Generated by Django 6.0.6 on 2026-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tournamentstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='max_wickets',
            field=models.PositiveIntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='total_overs',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
