# Generated by Django 6.0.6 on 2026-07-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_max_wickets_alter_match_total_overs'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentstanding',
            name='balls_bowled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='balls_faced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='runs_conceded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentstanding',
            name='runs_scored',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
