# Generated by Django 6.0.4 on 2026-05-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('scorer', 'Scorer'), ('captain', 'Captain'), ('player', 'Player'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
