# Generated by Django 6.0.6 on 2026-06-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authsystem', '0002_userprofile_bio'),
        ('matches', '0003_tournamentstanding'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('innings', models.PositiveIntegerField(choices=[(1, 'Innings 1'), (2, 'Innings 2')])),
                ('over', models.PositiveIntegerField()),
                ('ball_num', models.PositiveIntegerField()),
                ('runs', models.PositiveIntegerField(default=0)),
                ('extra_type', models.CharField(choices=[('none', 'None'), ('wd', 'Wide'), ('nb', 'No Ball'), ('lb', 'Leg Bye'), ('b', 'Bye')], default='none', max_length=10)),
                ('extra_runs', models.PositiveIntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batsman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_faced', to='authsystem.userprofile')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls_bowled', to='authsystem.userprofile')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='matches.match')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_balls', to='authsystem.userprofile')),
            ],
            options={
                'ordering': ['innings', 'over', 'ball_num'],
            },
        ),
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('current_innings', models.PositiveIntegerField(default=1)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_wickets', models.PositiveIntegerField(default=0)),
                ('total_balls', models.PositiveIntegerField(default=0)),
                ('innings1_runs', models.PositiveIntegerField(default=0)),
                ('innings1_wickets', models.PositiveIntegerField(default=0)),
                ('innings1_balls', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('current_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bowling', to='authsystem.userprofile')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_state', to='matches.match')),
                ('non_striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_non_striking', to='authsystem.userprofile')),
                ('striker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_striking', to='authsystem.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveIntegerField(default=0)),
                ('sixes', models.PositiveIntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_stats', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_batting', to='authsystem.userprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batting_innings', to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
        migrations.CreateModel(
            name='BowlingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('overs', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('runs_conceded', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveIntegerField(default=0)),
                ('maiden_overs', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_stats', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_bowling', to='authsystem.userprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bowling_innings', to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
