# Generated by Django 6.0.6 on 2026-07-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstate',
            name='current_rr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='innings1_rr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='innings2_balls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='innings2_rr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='innings2_runs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstate',
            name='innings2_wickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
